---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    checks:
      Similar code:
          enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "app/**/**.js"
exclude_paths: ["app/**/*_test.js", "e2e-tests/", "/**.js", ".eslintrc.js", "gulpfile.js", "karma.conf.js"]
